# Generated by Django 4.2.5 on 2023-10-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0003_remove_product_images_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(),
        ),
    ]
