# Generated by Django 4.2.5 on 2023-10-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0004_alter_product_original_price_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
