# Generated by Django 4.2.5 on 2023-10-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0007_remove_product_image_remove_product_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
