# Generated by Django 4.2.5 on 2023-10-04 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0010_category_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parent',
        ),
    ]
