# Generated by Django 4.2.5 on 2023-10-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0016_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.AddField(
            model_name='product',
            name='In_Stock',
            field=models.BooleanField(default=True),
        ),
    ]
