# Generated by Django 4.2.5 on 2023-10-06 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0017_remove_product_availability_product_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.TextField(max_length=700)),
                ('touch', models.TextField(max_length=700)),
                ('technology', models.TextField(max_length=700)),
                ('design', models.TextField(max_length=700)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='shope.product')),
            ],
        ),
    ]
