# Generated by Django 4.2.5 on 2023-10-06 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0019_alter_product_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='In_Stock',
            new_name='in_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_description', to='shope.product'),
        ),
        migrations.DeleteModel(
            name='FeaturedProducts',
        ),
    ]
