# Generated by Django 4.2.5 on 2023-10-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0020_rename_in_stock_product_in_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdescription',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='design',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='technology',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='touch',
        ),
        migrations.AddField(
            model_name='productdescription',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='title',
            field=models.CharField(default='', max_length=130),
        ),
    ]
