# Generated by Django 4.2.5 on 2023-10-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0023_category_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescription',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
