# Generated by Django 4.2.5 on 2023-10-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0025_product_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='arrival',
            field=models.BooleanField(default=''),
        ),
    ]
