# Generated by Django 4.2.5 on 2023-10-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0035_order_orderitem_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
