# Generated by Django 4.2.5 on 2023-10-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0041_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='product',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
