# Generated by Django 4.2.5 on 2023-10-20 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0042_remove_shippingaddress_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='user',
        ),
    ]
