# Generated by Django 4.2.5 on 2023-10-26 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0044_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddititonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_information', to='shope.product')),
            ],
        ),
    ]
