# Generated by Django 4.2.5 on 2023-10-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0047_ordertracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
