# Generated by Django 4.2.5 on 2023-11-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0048_category_slug_delete_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addititonalinformation',
            name='description',
        ),
        migrations.AddField(
            model_name='addititonalinformation',
            name='description1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='addititonalinformation',
            name='description2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='addititonalinformation',
            name='main_title1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
