# Generated by Django 4.2.5 on 2023-11-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0049_remove_addititonalinformation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addititonalinformation',
            name='main_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='addititonalinformation',
            name='main_title1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
